site_name: Daffodil

theme:
  name: material

nav:
  - Home: index.md
  - API:
      - Daf: api/daf.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            show_signature: true
            separate_signature: true