import sys
sys.path.insert(0, '/tmp/claude-0/-home-user-daffodil/95e36c09-64f8-59ba-9bd6-c962257ad9e3/scratchpad')
from annotate import apply
D = "'Daf'"
edits = {
  294: ('retmode', {}, 'str'),
  332: ('retmode', {'new_retmode': 'str'}, 'None'),
  347: ('itermode', {}, 'str'),
  386: ('itermode', {'new_itermode': 'str'}, 'None'),
  475: ('__bool__', {}, 'bool'),
  489: ('__format__', {'format_spec': 'str'}, 'str'),
  509: ('__eq__', {'other': 'object'}, 'bool'),
  545: ('__contains__', {'key': 'Any'}, None),
  598: ('__len__', {}, 'int'),
  608: ('num_rows', {}, 'int'),
  622: ('len', {}, 'int'),
  705: ('shape', {}, 'Tuple[int, int]'),
  767: ('_build_hd', {}, 'T_di'),
  789: ('columns', {}, 'T_ls'),
  800: ('_cols_to_hd', {}, 'None'),
  959: ('rename_cols', {}, D),
  982: ('set_cols', {}, D),
  1077: ('set_keyfield', {}, D),
  1179: ('_rebuild_kd_if_invalidated', {}, D),
  1246: ('_get_keyval', {'data_item': 'T_ma'}, 'Any'),
  1476: ('flatten', {'convert_bool_to_int': 'bool'}, D),
  2178: ('from_csv', {'kwargs': 'Any'}, D),
  2330: ('from_dirlist', {}, 'None'),
  2489: ('buff_to_file', {}, 'str'),
  2506: ('from_directory', {}, D),
  3021: ('append', {}, D),
  3095: ('concat', {}, D),
  3159: ('extend', {}, D),
  3207: ('record_append', {'respect_kd': 'bool'}, D),
  3338: ('remove_key', {'silent_error': 'bool'}, None),
  3365: ('remove_keylist', {'silent_error': 'bool'}, None),
  3545: ('_adjust_return_val', {}, 'Any'),
  5043: ('drop_cols', {}, D),
  5161: ('assign_record', {}, 'None'),
  5188: ('assign_record_irow', {}, 'None'),
  5207: ('update_by_keylist', {}, D),
  5231: ('update_record_irow', {}, 'None'),
  5260: ('assign_icol', {}, 'None'),
  5283: ('insert_icol', {}, D),
  5313: ('insert_irow', {}, D),
  5339: ('assign_col', {}, D),
  5364: ('insert_col', {}, D),
  5396: ('insert_idx_col', {'colname': 'str'}, None),
  5409: ('set_col_irows', {}, D),
  5429: ('set_icol', {}, D),
  5443: ('set_icol_irows', {}, 'None'),
  5462: ('find_replace', {'find_pat': 'str', 'replace_val': 'Any'}, 'None'),
  5622: ('apply_formulas', {}, 'None'),
  5943: ('update_row', {'row': 'T_ma', 'da': 'T_da'}, 'T_ma'),
  5948: ('apply_in_place', {}, 'None'),
  7322: ('set_col2_from_col1_using_regex_select', {}, 'None'),
  7502: ('apply_to_col', {'kwargs': 'Any'}, 'None'),
  7680: ('sum_dodis', {}, 'None'),
  8712: ('__iter__', {}, "'DafIterator[DafIterRtype]'"),
  8753: ('__init__', {'row': 'T_ma', 'indirect_col': 'str'}, None),
  8760: ('__getitem__', {'key': 'str'}, 'Any'),
  8770: ('get', {'key': 'str', 'default': 'Any'}, 'Any'),
  8781: ('keys', {}, 'Iterable[str]'),
  8790: ('values', {}, 'Iterable[Any]'),
  8797: ('items', {}, 'Iterable[Tuple[str, Any]]'),
  8287: ('fetch_record', {}, 'T_da'),
  6279: ('_iter_rows', {}, "Iterator['_IndirectRowView']"),
}
apply('src/daffodil/daf.py', edits, report=True)
