import sys
sys.breakpointhook = lambda *a, **k: print("BREAKPOINT")
from daffodil.daf import Daf
import daffodil.daf as dm
d = Daf(cols=['a','b'], lol=[[1,2],[3,4]])
try: d.iloc(0, rtype='bogus')
except Exception as e: print('iloc', type(e), e)
d2 = Daf(cols=['id','j'], lol=[['x','{"p": 1}'],['y','{"q": 2}'],['z', '{"p": 1}']])
print(d2.col_to_la('p', indirect_col='j', omit_nulls=True))
print(d2.col_to_la('p', indirect_col='j', default='D'))
print(d2.col_to_la('p', indirect_col='j', unique=True))
print(d2.col_to_la('p', indirect_col='j', default=None))
k = Daf(cols=['k','v'], lol=[['a',1],['b',2]], keyfield='k')
k.assign_col('k', ['c','d']); print(k.keys(), k.select_record('c'))
c = Daf(cols=['a','b','c'], lol=[[1,2,3],[4,5,6]], keyfield=['a','b'])
print(c.keyfield, c.keys())
c.replace_in_columns(['c'], find_values=[3], replacement=9); print(c.lol, c.keys())
c.replace_in_columns(['a'], find_values=[1], replacement=7); print(c.lol, c.keys())
try: d.copy().sort_by_colname('zz')
except Exception as e: print('sort', type(e), e)
try: d.copy().sort_by_colnames(['zz'])
except Exception as e: print('sorts', type(e), e)
print(Daf().apply_formulas(Daf()))
try: d.copy().apply_formulas(Daf(cols=['a'], lol=[['']]))
except Exception as e: print('af', type(e), e)
try: d.copy().apply_formulas(Daf(cols=['a','b'], lol=[['1/0',''],['','']]))
except Exception as e: print('af2', type(e), e)
x = Daf(cols=['a','b'], lol=[[1,10],[3,30],[6,60]])
print(x.copy().insert_dif_rows().lol)
print(x.copy().insert_dif_rows([0]).lol)
print(x.copy().insert_dif_rows([0,1], offset=1).lol)
