import sys
sys.breakpointhook = lambda *a, **k: print("BREAKPOINT")
from daffodil.daf import Daf
import daffodil.daf as dm
n = Daf(cols=['n','s'], lol=[[1,'a'],[2,'b'],[2,'c']])
r = n.gen_stats_daf([('n', int, '', 'index'), ('s', str, '', 'attrib')]); print({k: (v['profile'], v.get('num_uniques'), v.get('num_within_reps')) for k,v in r.items()})
t = Daf.derive_join_translator_daf('id', 'oid', ['id','name'], ['oid','name'], shared_fields=('x',))
print(t.lol)
sf = ['zz']
t = Daf.derive_join_translator_daf('id', 'oid', ['id','name'], ['oid','name'], shared_fields=sf); print(sf)
a = Daf(cols=['id','name'], lol=[[1,'A'],[2,'B']], keyfield='id')
b = Daf(cols=['id','sal'], lol=[[1,10],[3,30]], keyfield='id')
print(a.join(b, how='outer', diagnose=True).lol)
bad = Daf(cols=['foo'], lol=[[1]])
try: print(a.join(b, custom_translator_daf=bad).lol)
except Exception as e: print('j', type(e), e)
a2 = Daf(cols=['id','name'], lol=[[(1,2),'A']], keyfield='id')
b2 = Daf(cols=['id','sal'], lol=[[(1,2),10]], keyfield='id')
try: print(a2.join(b2).lol)
except Exception as e: print('j2', type(e), e)
c1 = Daf(cols=['a','b','v'], lol=[[1,2,3]], keyfield=['a','b'])
c2 = Daf(cols=['a','b','w'], lol=[[1,2,4]], keyfield=['a','b'])
try: print(c1.join(c2).lol)
except Exception as e: print('j3', type(e), e)
tr = Daf(cols=['resolved_colname','source_name','source_colname','is_keyfield'], lol=[['x','d1','x',False],['y','d2','y',False],['z','d3','z',False]])
try: Daf.join_records([{'x':1},{'y':2}], tr)
except Exception as e: print('jr', type(e), e)
print(Daf.join_records([{'x':1},{'y':2}], tr, ['d1','d2']))
print(Daf.join_records([{'x':1},None], tr, ['d1','d2']))
try: Daf.join_records([{'x':1},{'y':2}], Daf(cols=['resolved_colname','source_name','source_colname','is_keyfield']))
except Exception as e: print('jr2', type(e), e)
m = Daf(cols=['a'], lol=[[1]], name='nm'); m.attrs['schema'] = 'myschema'
print(m.to_md(include_summary=True))
print(Daf(cols=['a','b'], lol=[[1,2]]).daf_to_lol_summary(disp_cols=('X','Y')))
print(Daf(cols=['a','b'], lol=[[1,2]]).to_md_cols(disp_cols=('X','Y')))
v = Daf(cols=['a'], lol=[['x'],[''],['x'],['y']])
r = v.value_counts_daf('a', sort=True, include_total=True, omit_nulls=True); print(r.columns(), r.lol)
r = v.value_counts_daf('a'); print(r.columns(), r.lol)
u = Daf(cols=['id','j'], lol=[['r1', {'p': 1, 'q': 2}], ['r2', '{"p": 3}']])
print(dm.unpack_indirect(u, indirect_col='j', cols=['id','p','q'], default='D', silent_error=True).lol)
try: dm.unpack_indirect(u, indirect_col='j', cols=['id','q'], default='D')
except Exception as e: print('ui', type(e), e)
try: dm.unpack_indirect(u, indirect_col='nope', cols=['id'], default='D')
except Exception as e: print('ui2', type(e), e)
