import json
from daffodil.daf import Daf
from daffodil.keyedlist import KeyedList, KeyedIndex
def t(label, f):
    try: print(f'{label:46}', repr(f()))
    except Exception as e: print(f'{label:46}', type(e).__name__ + ':', str(e)[:70])

d = Daf(lol=[[1,'a'],[2,'b']], cols=['id','v'])
row = next(d.iter_klist())
print('--- keys')
t('type of keys()', lambda: type(row.keys()).__name__)
t('list(keys())', lambda: list(row.keys()))
print('--- values / set_values')
t('values() is the row of the Daf', lambda: row.values() is d.lol[0])
t('values(list) is the row', lambda: row.values(list) is d.lol[0])
k = KeyedList(['a','b'], ['1','2'])
t("values(int)", lambda: k.values(int))
t("values('float')", lambda: k.values('float'))
t("values(str.upper) callable", lambda: KeyedList(['a'], ['x']).values(str.upper))
t("values('date') bad name", lambda: k.values('date'))
t("values(int) not convertible", lambda: KeyedList(['a'], ['x']).values(int))
t("values(int) is a new list", lambda: k.values(int) is k.values())
r2 = next(d.iter_klist()); old = r2.values()
r2.set_values([10, 'z']); t('set_values: kl now', lambda: r2.values())
t('set_values: Daf row unchanged', lambda: d.lol[0])
t('set_values: wrong length', lambda: r2.set_values([1]))
t('set_values: tuple', lambda: r2.set_values((1,2)))
print('--- items / get / update / to_dict')
t('items() type', lambda: type(k.items()).__name__)
t('list(items())', lambda: list(k.items()))
it = k.items(); list(it); t('items() used up, second pass', lambda: list(it))
t('get missing', lambda: k.get('zz'))
t('get missing default', lambda: k.get('zz', 0))
t('get unhashable', lambda: k.get(['a']))
u = KeyedList(['a','b'], [1,2]); res = u.update({'b': 20, 'c': 30}); t('update returns', lambda: res)
t('update result', lambda: (u.to_dict(), u.values()))
u2 = KeyedList(['a','b'], [1,2]); u2.update(KeyedList(['b'], [9])); t('update from a KeyedList', lambda: u2.to_dict())
cell = [1, 2]; kd = KeyedList(['a'], [cell]); dd = kd.to_dict(); cell.append(3)
t('to_dict is shallow (list cell shared)', lambda: dd['a'])
kd2 = KeyedList(['a'], [1]); dd2 = kd2.to_dict(); kd2['a'] = 5
t('to_dict independent of later writes', lambda: dd2)
print('--- json')
j = KeyedList(['a','b'], [1, 'x']).to_json(); t('to_json', lambda: j)
t('from_json round trip', lambda: KeyedList.from_json(j).to_dict())
t('from_json int keys come back as str', lambda: KeyedList.from_json(KeyedList([1,2],[5,6]).to_json()).to_dict())
t('from_json other json', lambda: KeyedList.from_json('{"a": 1}'))
t('to_json value not serializable', lambda: KeyedList(['a'], [{1,2}]).to_json())
print('--- dunders')
t('len', lambda: len(k)); t('iter keys', lambda: list(k)); t("'a' in k", lambda: 'a' in k); t('repr', lambda: repr(k))
t('setitem new key', lambda: (lambda x: (x.__setitem__('c', 3), x.values(), list(x))[1:])(KeyedList(['a'], [1])))
t('delitem', lambda: (lambda x: (x.__delitem__('a'), x.values(), list(x))[1:])(KeyedList(['a','b'], [1,2])))
t('delitem missing', lambda: KeyedList(['a'], [1]).__delitem__('zz'))
print('--- KeyedIndex')
ki = KeyedIndex(['a','b'])
t('get', lambda: (ki.get('b'), ki.get('zz'), ki.get('zz', -1)))
t('index', lambda: ki.index('b')); t('index missing', lambda: ki.index('zz'))
t('keys type', lambda: type(ki.keys()).__name__)
t('append', lambda: (ki.append('c'), ki.to_dict())[1])
sh = KeyedIndex(ki); sh.append('d'); t('shared append shows in both', lambda: (list(ki), list(sh)))
t('to_dict is a copy', lambda: (lambda c: (c.update(z=9), 'z' in ki)[1])(ki.to_dict()))
