import os, tempfile
from pathlib import Path
from daffodil.daf import Daf, KeysDisabledError
from daffodil.keyedlist import KeyedList
d = Daf(lol=[[1,2],[3,4]], cols=['a','b'])
try: d.calc_cols(include_types=int)
except Exception as e: print('calc', type(e))
print(d.calc_cols(include_types=int) if False else '')
e = Daf(); print(e.record_append({}).lol)
e = Daf(); e.record_append(KeyedList({'a':1,'b':2})); print(e.hd, e.lol, type(e.hd))
k = Daf(cols=['a','b'], keyfield='a'); k.lol=[[1,2]]; k._invalidate_kd() if hasattr(k,'_invalidate_kd') else None
print(type(k._kd))
try: Daf(lol=[[1]],cols=['a']).remove_keylist(['x'])
except KeysDisabledError as ex: print('rk ok')
print(d._adjust_return_val(), d._adjust_return_val() is d)
try: Daf.gkeys_to_idxs({'a':0}, ())
except TypeError as ex: print('tuple', ex)
try: d.select_krows(['x'])
except KeysDisabledError: print('skr')
try: Daf(lol=[[1,2]]).select_kcols(['x'])
except KeysDisabledError: print('skc')
print(d.select_irows([], invert=True).lol, d.select_irows(None, invert=True).lol)
big = Daf(lol=[[i] for i in range(20)], cols=['a'])
print(big.select_irows(list(range(0,20,2)) + [1], invert=True).lol)
print(big.select_irows(list(range(15)), invert=True).lol)
print(big.select_irows([range(0,3), range(10,12)], invert=True).lol[:3], len(big.select_irows([range(0,3), range(10,12)], invert=True)))
w = Daf(lol=[[1,2,3],[4,5,6]], cols=['a','b','c'])
print(w.select_icols([range(0,1), range(2,3)], flip=True).lol)
uneven = Daf(lol=[[1,2,3],[4]], cols=['a','b','c'])
try: uneven.select_icols([0,2])
except IndexError: print('idx raised')
print(Daf(lol=[[1,2]],cols=['a','b'], keyfield='a').select_record(99, silent_error=False) if False else '')
try: Daf(lol=[[1,2]],cols=['a','b'], keyfield='a').select_record(99, silent_error=False)
except KeyError: print('keyerr')
print(d.select_records_daf([]).lol, d.select_records_daf([]).columns())
print(d.irow_la(1), d.irow_la(1) is d.lol[1])
print(d._is_keyfield_valid(('a','b')))
